### ISSUE TITLE
Cannot read property 'sizes' of undefined

### ISSUE THREAD

**Issue by ideask** [molavec/aircv-hexo-theme#4]
how can i fix that?

 Cannot read property 'sizes' of undefined
      at eval (/app/themes/hexo-theme-aircv/layout/_partial/head/opengraph.ejs:81:48)
      at opengraph (/app/node_modules/ejs/lib/ejs.js:682:17)
      at _View._compiledSync (/app/node_modules/hexo/lib/theme/view.js:132:24)
      at _View.renderSync (/app/node_modules/hexo/lib/theme/view.js:59:25)
      at Object.partial (/app/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
      at eval (/app/themes/hexo-theme-aircv/layout/_partial/head/index.ejs:24:17)
      at index (/app/node_modules/ejs/lib/ejs.js:682:17)
      at _View._compiledSync (/app/node_modules/hexo/lib/theme/view.js:132:24)
      at _View.renderSync (/app/node_modules/hexo/lib/theme/view.js:59:25)
      at Object.partial (/app/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
      at eval (/app/themes/hexo-theme-aircv/layout/layout.ejs:12:17)
      at layout (/app/node_modules/ejs/lib/ejs.js:682:17)
      at _View._compiled (/app/node_modules/hexo/lib/theme/view.js:136:50)
      at _View.render (/app/node_modules/hexo/lib/theme/view.js:39:17)
      at /app/node_modules/hexo/lib/theme/view.js:51:25
      at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9) {
    path: '/app/themes/hexo-theme-aircv/layout/layout.ejs'
  }

**Comment by ideask** [comment]
responsive_images:
  priority: 1
  pattern: '**/*.+(png|jpg|jpeg)'
  sizes:
    small:
      width: 200
    thumb:
      width: 400
    medium:
      width: 800
